### ISSUE TITLE
無法下載字幕

### ISSUE THREAD

**Issue by nova168168** [ChineseSubFinder/ChineseSubFinder#537]
安裝及設定好了，隊列中有兩個下載任務，但一直無法下載，不知道是甚麼問題？

系統資料如下：
Ｗindows 10 21H2
ChineseSubFinder 0.43.1
Chrome : 107.0.5304.88  (64bit)

Ｄebug Log :
DEBUG]: 2022-11-07 16:49:17 - Download.QueueDownloader() End
[WARNING]: 2022-11-07 16:49:17 - CloseChrome exit status 128
[INFO]: 2022-11-07 16:49:17 - CloseChrome End
[DEBUG]: 2022-11-07 16:49:32 - Download.QueueDownloader() Try Start ...
[DEBUG]: 2022-11-07 16:49:32 - Download.QueueDownloader() Start ...
[DEBUG]: 2022-11-07 16:49:32 - tOneJob.UpdateTime 2022-11-07 16:49:02.2924721 +0800 CST m=+57.323461201
[DEBUG]: 2022-11-07 16:49:32 - tOneJob.UpdateTime 2022-11-08 04:49:02.2924721 +0800 CST m=+43257.323461201
[DEBUG]: 2022-11-07 16:49:32 - tOneJob.UpdateTime is  true
[INFO]: 2022-11-07 16:49:32 - ------------------------------------------
[INFO]: 2022-11-07 16:49:32 - OneTimeSubtitleScanStart#c3850fb53f7a62aa60d469f4a8345d91d93c2498262758b454ad0f261e8018c5
[INFO]: 2022-11-07 16:49:32 - CloseChrome Start...
[INFO]: 2022-11-07 16:49:32 - OneTimeSubtitleScanEnd
[INFO]: 2022-11-07 16:49:32 - ------------------------------------------
[ERROR]: 2022-11-07 16:49:32 - Downloader.QueueDownloader() panic
[ERROR]: 2022-11-07 16:49:32 - goroutine 24770 [running]:
github.com/allanpk716/ChineseSubFinder/pkg.PrintPanicStack(0xc000316af0)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/util.go:710 +0x3d
github.com/allanpk716/ChineseSubFinder/pkg/downloader.(*Downloader).queueDownloaderLocal.func1()
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/downloader/queue_local.go:25 +0x7a
panic({0x1b34f20, 0x19cc9e0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1047 +0x266
github.com/allanpk716/ChineseSubFinder/pkg/downloader.(*Downloader).queueDownloaderLocal(0xc0004a6210)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/downloader/queue_local.go:302 +0x1c56
github.com/allanpk716/ChineseSubFinder/pkg/downloader.(*Downloader).QueueDownloader(0xc0004a6210)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/downloader/downloader.go:198 +0x1e
github.com/robfig/cron/v3.FuncJob.Run(0x4)
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.DelayIfStillRunning.func1.1()
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/chain.go:71 +0x1aa
github.com/robfig/cron/v3.FuncJob.Run(0xc0004be370)
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:131 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:307 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.0/cron.go:305 +0xb2

[DEBUG]: 2022-11-07 16:49:32 - Download.QueueDownloader() End
[WARNING]: 2022-11-07 16:49:32 - CloseChrome exit status 128
[INFO]: 2022-11-07 16:49:32 - CloseChrome End
[DEBUG]: 2022-11-07 16:49:47 - Download.QueueDownloader() Try Start ...
[DEBUG]: 2022-11-07 16:49:47 - Download.QueueDownloader() Start ...
[DEBUG]: 2022-11-07 16:49:47 - Download Queue Is Empty, Skip This Time
[DEBUG]: 2022-11-07 16:49:47 - Download.QueueDownloader() End
[DEBUG]: 2022-11-07 16:50:02 - Download.QueueDownloader() Try Start ...
[DEBUG]: 2022-11-07 16:50:02 - Download.QueueDownloader() Start ...
[DEBUG]: 2022-11-07 16:50:02 - Download Queue Is Empty, Skip This Time
[DEBUG]: 2022-11-07 16:50:02 - Download.QueueDownloader() End
[DEBUG]: 2022-11-07 16:50:17 - Download.QueueDownloader() Try Start ...
[DEBUG]: 2022-11-07 16:50:17 - Download.QueueDownloader() Start ...
[DEBUG]: 2022-11-07 16:50:17 - Download Queue Is Empty, Skip This Time
[DEBUG]: 2022-11-07 16:50:17 - Download.QueueDownloader() End
[DEBUG]: 2022-11-07 16:50:32 - Download.QueueDownloader() Try Start ...
[DEBUG]: 2022-11-07 16:50:32 - Download.QueueDownloader() Start ...
[DEBUG]: 2022-11-07 16:50:32 - Download Queue Is Empty, Skip This Time
[DEBUG]: 2022-11-07 16:50:32 - Download.QueueDownloader() End
[DEBUG]: 2022-11-07 16:50:47 - Download.QueueDownloader() Try Start ...
[DEBUG]: 2022-11-07 16:50:47 - Download.QueueDownloader() Start ...
[DEBUG]: 2022-11-07 16:50:47 - Download Queue Is Empty, Skip This Time

**Comment by allanpk716** [comment]
先删除 cache 缓存文件夹，再试

**Comment by allanpk716** [comment]
可见范围内的异常我看都处理了，但是还是有 panic 出现，暂时没有什么想法。确认下缓存文件是否正确，以及由权限写入

**Comment by nova168168** [comment]
重建了緩存還是一樣, Chrome錯誤退出!

INFO]: 2022-11-09 23:04:51 - ------------------------------------------
[INFO]: 2022-11-09 23:04:51 -
OneTimeSubtitleScanStart#c3850fb53f7a62aa60d469f4a8345d91d93c2498262758b454ad0f261e8018c5
[INFO]: 2022-11-09 23:04:51 - OneTimeSubtitleScanEnd
[INFO]: 2022-11-09 23:04:51 - ------------------------------------------
[ERROR]: 2022-11-09 23:04:51 - Downloader.QueueDownloader() panic
[INFO]: 2022-11-09 23:04:51 - CloseChrome Start...
[ERROR]: 2022-11-09 23:04:51 - goroutine 41835 [running]:
github.com/allanpk716/ChineseSubFinder/pkg.PrintPanicStack(0xc0006868c0)
/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/util.go:710 +0x3d
github.com/allanpk716/ChineseSubFinder/pkg/downloader.(*Downloader).queueDownloaderLocal.func1()
/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/downloader/queue_local.go:25
+0x7a
panic({0x1bc4f20, 0x1a5c9e0})
/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1047 +0x266
github.com/allanpk716/ChineseSubFinder/pkg/downloader.(*Downloader).queueDownloaderLocal(0xc00088c0b0)
/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/downloader/queue_local.go:302
+0x1c56
github.com/allanpk716/ChineseSubFinder/pkg/downloader.(*Downloader).QueueDownloader(0xc00088c0b0)
/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/downloader/downloader.go:198
+0x1e
github.com/robfig/cron/v3.FuncJob.Run(0x4)
***@***.***/cron.go:131 +0x1a
github.com/robfig/cron/v3.DelayIfStillRunning.func1.1()
***@***.***/chain.go:71 +0x1aa
github.com/robfig/cron/v3.FuncJob.Run(0xc000724050)
***@***.***/cron.go:131 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
***@***.***/cron.go:307 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
***@***.***/cron.go:305 +0xb2

[DEBUG]: 2022-11-09 23:04:51 - Download.QueueDownloader() End
[INFO]: 2022-11-09 23:04:51 - CloseChrome End
[DEBUG]: 2022-11-09 23:05:06 - Download.QueueDownloader() Try Start ...
[DEBUG]: 2022-11-09 23:05:06 - Download.QueueDownloader() Start ...
[DEBUG]: 2022-11-09 23:05:06 - Download Queue Is Empty, Skip This Time
[DEBUG]: 2022-11-09 23:05:06 - Download.QueueDownloader() End
[DEBUG]: 2022-11-09 23:05:21 - Download.QueueDownloader() Try Start ...
[DEBUG]: 2022-11-09 23:05:21 - Download.QueueDownloader() Start ...
[DEBUG]: 2022-11-09 23:05:21 - Download Queue Is Empty, Skip This Time
[DEBUG]: 2022-11-09 23:05:21 - Download.QueueDownloader() End
