### ISSUE TITLE
软件在虚拟机内无法运行

### ISSUE THREAD

**Issue by ajdgsu** [ChineseSubFinder/ChineseSubFinder#605]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.46.3
>
> 环境: ubuntu 22.10 虚拟机直接运行
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 虚拟机内无法运行 chinesesubfinder，直接崩溃；实体机 (truenas) 可以正常允许

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 正常运行程序

## 给出当前程序的配置文件

> 软件完全无法运行，甚至连初始的配置文件都没有被创建出来

## 请给出当次问题的完整日志

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1f7560 pc=0x7fee74433ad6]

runtime stack:
runtime.throw({0x138aac6, 0x353})
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/signal_unix.go:719 +0x389

goroutine 7 [syscall]:
runtime.cgocall(0xec0600, 0xc00005c590)
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc00005c568 sp=0xc00005c530 pc=0x405e1c
net._C2func_getaddrinfo(0xc00003c900, 0x0, 0xc0001d4390, 0xc000010108)
	_cgo_gotypes.go:91 +0x56 fp=0xc00005c590 sp=0xc00005c568 pc=0x5fd6b6
net.cgoLookupIPCNAME.func1({0xc00003c900, 0x0, 0x0}, 0xc000128000, 0xc00005c650)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc00005c5e8 sp=0xc00005c590 pc=0x5ff3ff
net.cgoLookupIPCNAME({0x1338129, 0x3}, {0xc000128000, 0x5})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc00005c738 sp=0xc00005c5e8 pc=0x5fec4d
net.cgoIPLookup(0x2c86d90, {0x1338129, 0xc00003c8c0}, {0xc000128000, 0xc00012e000})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc00005c7a8 sp=0xc00005c738 pc=0x5ff4bb
net.cgoLookupIP·dwrap·25()
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc00005c7e0 sp=0xc00005c7a8 pc=0x5ff936
runtime.goexit()
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0x469ae1
created by net.cgoLookupIP
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:230 +0x125

goroutine 1 [select, locked to thread]:
net/http.(*Transport).getConn(0xc00010e000, 0xc000126000, {{}, 0x0, {0xc000098180, 0x5}, {0xc000128000, 0x1d}, 0x0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc00010e000, 0xc000118000)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc0001a95a8, 0x1e6a140)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/roundtrip.go:18 +0x19
net/http.send(0xc000118000, {0x1e6a140, 0xc00010e000}, {0x12f4880, 0x1, 0x0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc000114000, 0xc000118000, {0xc000118000, 0x24, 0x0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc000114000, 0xc000118000)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:593
github.com/EDDYCJY/fake-useragent/downloader.(*Download).Get(0xc0001a9a08, {0xc000098180, 0x60})
	/home/runner/go/pkg/mod/github.com/!e!d!d!y!c!j!y/fake-useragent@v0.2.0/downloader/http.go:37 +0x188
github.com/EDDYCJY/fake-useragent/useragent/cache.(*raw).Get(0x136b512)
	/home/runner/go/pkg/mod/github.com/!e!d!d!y!c!j!y/fake-useragent@v0.2.0/useragent/cache/rawgithub.go:32 +0x45
github.com/allanpk716/fake-useragent.(*browser).load(0xc00003c820)
	/home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:77 +0x2c6
github.com/allanpk716/fake-useragent.NewBrowser({0xc0001a9bc8, 0x26f5268, 0x139a5d2}, {0x4a})
	/home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:51 +0x90
github.com/allanpk716/fake-useragent.init()
	/home/runner/go/pkg/mod/github.com/allanpk716/fake-useragent@v0.2.1/b.go:30 +0x2f

goroutine 18 [select]:
net.(*Resolver).lookupIPAddr(0x2c86d80, {0x1e82110, 0xc00008c840}, {0x1338129, 0xc000096a00}, {0xc000128000, 0x19})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0x1e82110, {0x1e82110, 0xc00008c840}, {0x1338129, 0x3}, {0xc000128000, 0x1d})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0x2cc5130, {0x1e82110, 0xc00008c840}, {0x1339a09, 0x4}, {0x1338129, 0xc0000e68d8}, {0xc000128000, 0x1d}, {0x0, ...})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0xc000112000, {0x1e820d8, 0xc0000360a0}, {0x1338129, 0x7fee9d436fd8}, {0xc000128000, 0x118})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/dial.go:406 +0x448
net/http.(*Transport).dial(0x0, {0x1e820d8, 0xc0000360a0}, {0x1338129, 0x0}, {0xc000128000, 0x0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1166 +0xda
net/http.(*Transport).dialConn(0xc00010e000, {0x1e820d8, 0xc0000360a0}, {{}, 0x0, {0xc000098180, 0x5}, {0xc000128000, 0x1d}, 0x0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x0, 0xc00012e000)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1415 +0x3d7

goroutine 6 [select]:
net.cgoLookupIP({0x1e820a0, 0xc00008a8c0}, {0x1338129, 0x19}, {0xc000128000, 0x0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x2c86d80, {0x1e820a0, 0xc00008a8c0}, {0x1338129, 0x3}, {0xc000128000, 0x19})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x1e820a0, 0xc00008a8c0}, 0x0, {0x1338129, 0x0}, {0xc000128000, 0x6f3e30})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x2c86d90, 0xc000096a50, {0xc00003c8c0, 0x1d}, 0xc00012e000)
	/opt/hostedtoolcache/go/1.17.13/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/opt/hostedtoolcache/go/1.17.13/x64/src/internal/singleflight/singleflight.go:88 +0x2f1

PS: 这是虚拟机的配置选项，我不知道这些配置文件被放在哪里了，所以只能给出图片，抱歉
![Screenshot_2023-01-17-00-15-42-105_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/45306865/212724458-999ca2e2-986c-482a-8406-2c7a4549903d.jpg)

**Comment by allanpk716** [comment]
看起来是支持库的问题，我对 linux 不太熟悉
