### ISSUE TITLE
威联通系统终端直接运行二进制文件报错

### ISSUE THREAD

**Issue by Mojelly** [ChineseSubFinder/ChineseSubFinder#708]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: 5.3.0~5.4.4
>
> 环境: 威联通NAS系统，x86_64和arm64架构
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 直接在威联通下通过ssh命令行运行出现报错，浏览器无法访问19035端口

终端运行报错信息如下：
[INFO]: 2023-10-08 16:52:15 - LiteMode is true
[INFO]: 2023-10-08 16:52:15 - ChineseSubFinder Version: v0.53.0 Lite
[INFO]: 2023-10-08 16:52:15 - Reload Log Settings, level = Info
[INFO]: 2023-10-08 16:52:15 - SetLinuxConfigPathInSelfPath: ./config
[INFO]: 2023-10-08 16:52:15 - Speed Dev Mode is Off
[INFO]: 2023-10-08 16:52:15 - PreJob.HotFix() Start...
[INFO]: 2023-10-08 16:52:15 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2023-10-08 16:52:15 - PreJob.HotFix() End
[INFO]: 2023-10-08 16:52:15 - PreJob.ChangeSubNameFormat() Start...
[INFO]: 2023-10-08 16:52:15 - If you have a lot of videos, it may take a lot of time, just wait...
[INFO]: 2023-10-08 16:52:15 - DesSubFormatter == LateTimeSubFormatter then skip process
[INFO]: 2023-10-08 16:52:15 - PreJob.ChangeSubNameFormat() End
[INFO]: 2023-10-08 16:52:15 - PreJob.Wait() Done.
[INFO]: 2023-10-08 16:52:15 - Download.SupplierCheck() Start ...
[INFO]: 2023-10-08 16:52:15 - PreDownloadProcess.Init().Check().Wait()...
[INFO]: 2023-10-08 16:52:15 - PreDownloadProcess.Init() Start...
[INFO]: 2023-10-08 16:52:15 - ClearRodTmpRootFolder Done
[INFO]: 2023-10-08 16:52:15 - PreDownloadProcess.Init() End
[INFO]: 2023-10-08 16:52:15 - PreDownloadProcess.Check() Start...
[INFO]: 2023-10-08 16:52:15 - UseHttpProxy = false
[INFO]: 2023-10-08 16:52:15 - UrlConnectednessTest Target Site https://baidu.com Speed: 315 ms, Status: true
[INFO]: 2023-10-08 16:52:15 - Check Sub Supplier Start...
[INFO]: 2023-10-08 16:52:15 - xunlei Check Alive = true, Speed = 61 ms
[INFO]: 2023-10-08 16:52:30 - shooter Check Alive = true, Speed = 14683 ms
chinesesubfinder: dl-call-libc-early-init.c:37: _dl_call_libc_early_init: Assertion `sym != NULL' failed.
SIGABRT: abort
PC=0x1010c7c m=4 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x1010c7c
stack: frame={sp:0x7ff90d609d90, fp:0x0} stack=[0x7ff90ce0b550,0x7ff90d60b150)
0x00007ff90d609c90:  0x0000000000000000  0x00007ff904000fb0 
0x00007ff90d609ca0:  0x0000000000000002  0x0000003200000008 
0x00007ff90d609cb0:  0x0000000000000000  0x0000000000000000 
0x00007ff90d609cc0:  0x0000000000000000  0x000000770000007c 
0x00007ff90d609cd0:  0x0000005b0000006e  0xb6513af6e9653f00 
0x00007ff90d609ce0:  0x0000000000002118  0xffffffffffffffa8 
0x00007ff90d609cf0:  0x0000000000000000  0x000000000000006a 
0x00007ff90d609d00:  0x000000000000006b  0x00007ff9040041a0 
0x00007ff90d609d10:  0x00007ff90d609d60  0x0000000001018ad1 
0x00007ff90d609d20:  0x00007ff904004130  0x0000000002102558 
0x00007ff90d609d30:  0x00007ff90d609ea0  0x00007ff90d609fb0 
0x00007ff90d609d40:  0x000000000000006a  0x0000000001007036 
0x00007ff90d609d50:  0x0000000001018720  0x0000000001018a60 
0x00007ff90d609d60:  0x00007ff9fbad8000  0x00007ff9040041a0 
0x00007ff90d609d70:  0x00007ff904004205  0x00007ff9040041a0 
0x00007ff90d609d80:  0x00007ff9040041a0  0x0000000001010c6e 
0x00007ff90d609d90: <0x00007ff9040042cc  0x00007ff9040041a0 
0x00007ff90d609da0:  0x00007ff9040042cc  0x0000000000000000 
0x00007ff90d609db0:  0x0000000000000000  0x0000000000000000 
0x00007ff90d609dc0:  0x0000000000000000  0x0000000000000000 
0x00007ff90d609dd0:  0x0000008000000001  0x0000000000000006 
0x00007ff90d609de0:  0x00007ff904000000  0x0000000000000000 
0x00007ff90d609df0:  0x000000000000006e  0xb6513af6e9653f00 
0x00007ff90d609e00:  0xffffffffffffffff  0xb6513af6e9653f00 
0x00007ff90d609e10:  0x000000000286ecc0  0xb6513af6e9653f00 
0x00007ff90d609e20:  0x00007ff90d60b640  0x0000000000000006 
0x00007ff90d609e30:  0x000000000211c4da  0x0000000000000025 
0x00007ff90d609e40:  0x000000000210be13  0x0000000000ffc016 
0x00007ff90d609e50:  0x0000000002a70180  0x0000000000401cf5 
0x00007ff90d609e60:  0x0000000000000020  0x000000000286ecc0 
0x00007ff90d609e70:  0x000000000211c4da  0x0000000000000025 
0x00007ff90d609e80:  0x000000000210be13  0x00007ff904002b40 
runtime: unknown pc 0x1010c7c
stack: frame={sp:0x7ff90d609d90, fp:0x0} stack=[0x7ff90ce0b550,0x7ff90d60b150)
0x00007ff90d609c90:  0x0000000000000000  0x00007ff904000fb0 
0x00007ff90d609ca0:  0x0000000000000002  0x0000003200000008 
0x00007ff90d609cb0:  0x0000000000000000  0x0000000000000000 
0x00007ff90d609cc0:  0x0000000000000000  0x000000770000007c 
0x00007ff90d609cd0:  0x0000005b0000006e  0xb6513af6e9653f00 
0x00007ff90d609ce0:  0x0000000000002118  0xffffffffffffffa8 
0x00007ff90d609cf0:  0x0000000000000000  0x000000000000006a 
0x00007ff90d609d00:  0x000000000000006b  0x00007ff9040041a0 
0x00007ff90d609d10:  0x00007ff90d609d60  0x0000000001018ad1 
0x00007ff90d609d20:  0x00007ff904004130  0x0000000002102558 
0x00007ff90d609d30:  0x00007ff90d609ea0  0x00007ff90d609fb0 
0x00007ff90d609d40:  0x000000000000006a  0x0000000001007036 
0x00007ff90d609d50:  0x0000000001018720  0x0000000001018a60 
0x00007ff90d609d60:  0x00007ff9fbad8000  0x00007ff9040041a0 
0x00007ff90d609d70:  0x00007ff904004205  0x00007ff9040041a0 
0x00007ff90d609d80:  0x00007ff9040041a0  0x0000000001010c6e 
0x00007ff90d609d90: <0x00007ff9040042cc  0x00007ff9040041a0 
0x00007ff90d609da0:  0x00007ff9040042cc  0x0000000000000000 
0x00007ff90d609db0:  0x0000000000000000  0x0000000000000000 
0x00007ff90d609dc0:  0x0000000000000000  0x0000000000000000 
0x00007ff90d609dd0:  0x0000008000000001  0x0000000000000006 
0x00007ff90d609de0:  0x00007ff904000000  0x0000000000000000 
0x00007ff90d609df0:  0x000000000000006e  0xb6513af6e9653f00 
0x00007ff90d609e00:  0xffffffffffffffff  0xb6513af6e9653f00 
0x00007ff90d609e10:  0x000000000286ecc0  0xb6513af6e9653f00 
0x00007ff90d609e20:  0x00007ff90d60b640  0x0000000000000006 
0x00007ff90d609e30:  0x000000000211c4da  0x0000000000000025 
0x00007ff90d609e40:  0x000000000210be13  0x0000000000ffc016 
0x00007ff90d609e50:  0x0000000002a70180  0x0000000000401cf5 
0x00007ff90d609e60:  0x0000000000000020  0x000000000286ecc0 
0x00007ff90d609e70:  0x000000000211c4da  0x0000000000000025 
0x00007ff90d609e80:  0x000000000210be13  0x00007ff904002b40 

goroutine 23 [syscall]:
runtime.cgocall(0xef72f0, 0xc000114d90)
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc000114d68 sp=0xc000114d30 pc=0x405e3c
net._C2func_getaddrinfo(0xc000660f10, 0x0, 0xc000cb0720, 0xc000010090)
	_cgo_gotypes.go:91 +0x56 fp=0xc000114d90 sp=0xc000114d68 pc=0x5fe756
net.cgoLookupIPCNAME.func1({0xc000660f10, 0x44af6f, 0xc000114fb0}, 0xc000660ef0, 0xc000114e50)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc000114de8 sp=0xc000114d90 pc=0x60049f
net.cgoLookupIPCNAME({0x137c904, 0x3}, {0xc000660ef0, 0x5})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc000114f38 sp=0xc000114de8 pc=0x5ffced
net.cgoIPLookup(0x2a375d0, {0x137c904, 0xc000660f00}, {0xc000660ef0, 0xc000cc6160})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc000114fa8 sp=0xc000114f38 pc=0x60055b
net.cgoLookupIP·dwrap·25()
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc000114fe0 sp=0xc000114fa8 pc=0x6009d6
runtime.goexit()
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000114fe8 sp=0xc000114fe0 pc=0x469ba1
created by net.cgoLookupIP
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:230 +0x125

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc0002fe640, 0xc0004c2780, {{}, 0x0, {0xc0008e4048, 0x5}, {0xc000660ef0, 0xf}, 0x0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1372 +0x5d2
net/http.(*Transport).roundTrip(0xc0002fe640, 0xc000cc4200)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:581 +0x774
net/http.(*Transport).RoundTrip(0xc000cc4200, 0x1fef840)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/roundtrip.go:18 +0x19
net/http.send(0xc000cc4100, {0x1fef840, 0xc0002fe640}, {0x13382a0, 0x4c8401, 0x2a38ba0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc000cb0360, 0xc000cc4100, {0x0, 0x130c900, 0x2a38ba0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc000cb0360, 0xc000cc4100)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/client.go:593
github.com/go-resty/resty/v2.(*Client).execute(0xc0001741e0, 0xc0005224e0)
	/home/runner/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/client.go:932 +0x413
github.com/go-resty/resty/v2.(*Request).Execute.func1()
	/home/runner/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:769 +0x89
github.com/go-resty/resty/v2.Backoff(0xc000be15a8, {0xc000be1580, 0x5, 0x4b})
	/home/runner/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/retry.go:105 +0x1aa
github.com/go-resty/resty/v2.(*Request).Execute(0xc0005224e0, {0x137a495, 0x0}, {0xc0008e4030, 0x13})
	/home/runner/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:763 +0x552
github.com/go-resty/resty/v2.(*Request).Get(...)
	/home/runner/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:689
github.com/ChineseSubFinder/ChineseSubFinder/pkg/logic/sub_supplier/a4k.(*Supplier).CheckAlive(0xc000775cf8)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/logic/sub_supplier/a4k/a4k.go:61 +0x325
github.com/ChineseSubFinder/ChineseSubFinder/pkg/logic/sub_supplier.(*SubSupplierHub).CheckSubSiteStatus(0xc000792e40)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/logic/sub_supplier/subSupplierHub.go:192 +0x3eb
github.com/ChineseSubFinder/ChineseSubFinder/pkg/logic/pre_download_process.(*PreDownloadProcess).Check(0xc000be1cd0)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/logic/pre_download_process/pre_download_proces.go:183 +0x60a
github.com/ChineseSubFinder/ChineseSubFinder/pkg/downloader.(*Downloader).SupplierCheck(0xc00014cd10)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/downloader/downloader.go:161 +0x1ee
github.com/ChineseSubFinder/ChineseSubFinder/pkg/logic/cron_helper.NewCronHelper(0xc000792a40)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/logic/cron_helper/cron_helper.go:69 +0x18c
main.main()
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/cmd/chinesesubfinder/main.go:161 +0x2df

goroutine 8 [select]:
github.com/panjf2000/ants/v2.(*Pool).purgePeriodically(0xc0000a5c80, {0x20085e0, 0xc0004c2200})
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.6.0/pool.go:78 +0x11c
created by github.com/panjf2000/ants/v2.NewPool
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.6.0/pool.go:157 +0x37e

goroutine 35 [select]:
database/sql.(*DB).connectionOpener(0xc00029c340, {0x20085e0, 0xc000152380})
	/opt/hostedtoolcache/go/1.17.13/x64/src/database/sql/sql.go:1196 +0x93
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.17.13/x64/src/database/sql/sql.go:794 +0x188

goroutine 22 [select]:
net.cgoLookupIP({0x20085e0, 0xc0004c27c0}, {0x137c904, 0xb}, {0xc000660ef0, 0xe})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x2a375c0, {0x20085e0, 0xc0004c27c0}, {0x137c904, 0x3}, {0xc000660ef0, 0xb})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x20085e0, 0xc0004c27c0}, 0xc000114f7c, {0x137c904, 0xc000114fb8}, {0xc000660ef0, 0x6f4ed0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x2a375d0, 0xc000cb8140, {0xc000660f00, 0xf}, 0xc000cc6160)
	/opt/hostedtoolcache/go/1.17.13/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
	/opt/hostedtoolcache/go/1.17.13/x64/src/internal/singleflight/singleflight.go:88 +0x2f1

goroutine 37 [select]:
database/sql.(*DB).connectionOpener(0xc00077b040, {0x20085e0, 0xc000725c00})
	/opt/hostedtoolcache/go/1.17.13/x64/src/database/sql/sql.go:1196 +0x93
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.17.13/x64/src/database/sql/sql.go:794 +0x188

goroutine 38 [select]:
github.com/panjf2000/ants/v2.(*PoolWithFunc).purgePeriodically(0xc000795d40, {0x20085e0, 0xc000781ac0})
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.6.0/pool_func.go:80 +0x158
created by github.com/panjf2000/ants/v2.NewPoolWithFunc
	/home/runner/go/pkg/mod/github.com/panjf2000/ants/v2@v2.6.0/pool_func.go:174 +0x305

goroutine 39 [chan receive]:
github.com/ChineseSubFinder/ChineseSubFinder/pkg/manual_upload_sub_2_local.NewManualUploadSub2Local.func1(0xc0007ac300)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/manual_upload_sub_2_local/processor.go:60 +0x30
created by github.com/ChineseSubFinder/ChineseSubFinder/pkg/manual_upload_sub_2_local.NewManualUploadSub2Local
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/manual_upload_sub_2_local/processor.go:57 +0x305

goroutine 40 [chan receive]:
github.com/ChineseSubFinder/ChineseSubFinder/pkg/preview_queue.NewPreviewQueue.func1(0xc000773e60)
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/preview_queue/queue.go:45 +0x27
created by github.com/ChineseSubFinder/ChineseSubFinder/pkg/preview_queue.NewPreviewQueue
	/home/runner/work/ChineseSubFinder/ChineseSubFinder/pkg/preview_queue/queue.go:42 +0x1a5

goroutine 21 [select]:
net.(*Resolver).lookupIPAddr(0x2a375c0, {0x2008650, 0xc000cb6300}, {0x137c904, 0x0}, {0xc000660ef0, 0xb})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0x2008650, {0x2008650, 0xc000cb6300}, {0x137c904, 0x3}, {0xc000660ef0, 0xf})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0x2a75c20, {0x2008650, 0xc000cb6300}, {0x137e328, 0x4}, {0x137c904, 0xc000061910}, {0xc000660ef0, 0xf}, {0x0, ...})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0x2a38a40, {0x2008650, 0xc000cb6300}, {0x137c904, 0xc000061a40}, {0xc000660ef0, 0x118})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/dial.go:406 +0x448
net/http.(*Transport).dial(0xc000cb6300, {0x2008650, 0xc000cb6300}, {0x137c904, 0xc000061ab8}, {0xc000660ef0, 0x203000})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1175 +0xb8
net/http.(*Transport).dialConn(0xc0002fe640, {0x2008650, 0xc000cb6300}, {{}, 0x0, {0xc0008e4048, 0x5}, {0xc000660ef0, 0xf}, 0x0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1604 +0x845
net/http.(*Transport).dialConnFor(0x6f7da6, 0xc000cc6160)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1446 +0xb0
created by net/http.(*Transport).queueForDial
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1415 +0x3d7

goroutine 47 [IO wait]:
internal/poll.runtime_pollWait(0x7ff90c59b188, 0x72)
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc0007ac480, 0xc0007d0000, 0x0)
	/opt/hostedtoolcache/go/1.17.13/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.17.13/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0007ac480, {0xc0007d0000, 0x10e2, 0x10e2})
	/opt/hostedtoolcache/go/1.17.13/x64/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0007ac480, {0xc0007d0000, 0xc0007d000d, 0x175})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00053d320, {0xc0007d0000, 0x10d5, 0xc0000637f8})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00017e138, {0xc0007d0000, 0x0, 0x40c94d})
	/opt/hostedtoolcache/go/1.17.13/x64/src/crypto/tls/conn.go:778 +0x3d
bytes.(*Buffer).ReadFrom(0xc00078fe78, {0x1fedbc0, 0xc00017e138})
	/opt/hostedtoolcache/go/1.17.13/x64/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00078fc00, {0x1fef780, 0xc00053d320}, 0x7ff90e785400)
	/opt/hostedtoolcache/go/1.17.13/x64/src/crypto/tls/conn.go:800 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00078fc00, 0x0)
	/opt/hostedtoolcache/go/1.17.13/x64/src/crypto/tls/conn.go:607 +0x112
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.17.13/x64/src/crypto/tls/conn.go:575
crypto/tls.(*Conn).Read(0xc00078fc00, {0xc0001ce000, 0x1000, 0x1})
	/opt/hostedtoolcache/go/1.17.13/x64/src/crypto/tls/conn.go:1278 +0x16f
net/http.(*persistConn).Read(0xc000709c20, {0xc0001ce000, 0xc0007ca060, 0xc000063d30})
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc000773c80)
	/opt/hostedtoolcache/go/1.17.13/x64/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc000773c80, 0x1)
	/opt/hostedtoolcache/go/1.17.13/x64/src/bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc000709c20)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1747 +0x1e05

goroutine 48 [select]:
net/http.(*persistConn).writeLoop(0xc000709c20)
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
	/opt/hostedtoolcache/go/1.17.13/x64/src/net/http/transport.go:1748 +0x1e65

rax    0x0
rbx    0x7ff90d60b640
rcx    0x1010c7c
rdx    0x6
rdi    0x58e8
rsi    0x592a
rbp    0x592a
rsp    0x7ff90d609d90
r8     0x7ff90d609e60
r9     0x0
r10    0x8
r11    0x246
r12    0x6
r13    0x16
r14    0x210be13
r15    0x7ff904002b40
rip    0x1010c7c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

## 你的问题弄重现嘛？

> 能够重现

## 你期望的结果

> 希望二进制文件兼容威联通系统，能正常初始化运行，早期打包威联通qpkg安装包时，可以正常访问并初始化运行，猜测应该和威联通的系统固件版本升级有关系，不过其他二进制软件运行无异。

## 给出当前程序的配置文件
未完成初始化，暂无配置文件。

**Comment by allanpk716** [comment]
1. 必发吗？
2. 你能够把多次启动就崩溃的日志，一次崩溃一个日志文件的提交上来吗？

**Comment by MARINGTIN** [comment]
我也是威联通升级后就不能用，程序文件夹里不会生成Log，proteiner直接看启动后日志就两句话

> 已设置 PERMS=true，重设 '/media' 目录权限为 1026:100 所有（媒体文件多，花的时间也多，耐心等）...
> 检测到映射了 '/app/cache'，创建软连接 '/config/cache' -> '/app/cache'（如果原有缓存多，花的时间也多，耐心等）

**Comment by allanpk716** [comment]
1. 日志要再发一次，我需要确定故障的点是否一样。目前日志看起来故障的问题是设置 http client 的时候出问题了，这种问题就不应该出现。
2. 使用最新的 docker 镜像再反馈。

**Comment by allanpk716** [comment]
> 我也是威联通升级后就不能用，程序文件夹里不会生成Log，portainer直接看启动后日志就两句话
> 
> > 已设置 PERMS=true，重设 '/media' 目录权限为 1026:100 所有（媒体文件多，花的时间也多，耐心等）...
> > 检测到映射了 '/app/cache'，创建软连接 '/config/cache' -> '/app/cache'（如果原有缓存多，花的时间也多，耐心等）

这两句话意思是明确的

**Comment by allanpk716** [comment]
> > 1. 日志要再发一次，我需要确定故障的点是否一样。目前日志看起来故障的问题是设置 http client 的时候出问题了，这种问题就不应该出现。
> > 2. 使用最新的 docker 镜像再反馈。
> 
> 今天重新用最新版（0.55.1）二进制文件，在终端直接运行（不是Docker镜像方式） 有个神奇的情况，有一台威联通x86_64架构的qts hero系统（zfs）在报错几次后，成功启动，网页初始化完成后，再次反复重启，没有出现异常了。另一个x86_64的qts系统，终端运行二进制文件依旧报错，还有一台arm64架构的威联通qts系统，也是一样报错无法正常初始化。
> 
> 下面是x86_64架构和arm64架构各自运行5次后的错误信息。 https://www.aliyundrive.com/s/X6o3LJkb8XG

这里的报错都是一样的，没有思路如何解决，因为仅仅是做 http 请求而已
