### ISSUE TITLE
unraid6.11.5下ChineseSubFinder经常自动停止

### ISSUE THREAD

**Issue by kpnew9** [ChineseSubFinder/ChineseSubFinder#721]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.55.2 Lite
>
> 环境: docker （unraid6.11.5）
>

## 你遇到什么问题了？

unraid6.11.5下ChineseSubFinder经常自动停止

## 你的问题弄重现嘛？

> 能够重新

## 你期望的结果

> 不要自动停止

## 给出当前程序的配置文件

{
    "SpeedDevMode":false,
    "user_info":{
        "username":"*",
        "password":"*"
    },
    "common_settings":{
        "interval_or_assign_or_custom":0,
        "scan_interval":"@every 4h",
        "threads":3,
        "run_scan_at_start_up":false,
        "movie_paths":[
            "/media/movie"
        ],
        "series_paths":[
            "/media/Episodes"
        ],
        "local_static_file_port":"19037"
    },
    "subtitle_sources":{
        "assrt_settings":{
            "enabled":true,
            "token":"*"
        },
        "subtitle_best_settings":{
            "enabled":true,
            "api_key":"*"
        }
    },
    "advanced_settings":{
        "proxy_settings":{
            "use_proxy":false,
            "use_which_proxy_protocol":"http",
            "local_http_proxy_server_port":"19036",
            "input_proxy_address":"127.0.0.1",
            "input_proxy_port":"10809",
            "need_pwd":false,
            "input_proxy_username":"",
            "input_proxy_password":""
        },
        "tmdb_api_settings":{
            "enable":false,
            "api_key":"",
            "use_alternate_base_url":false
        },
        "debug_mode":false,
        "save_full_season_tmp_subtitles":false,
        "sub_type_priority":0,
        "sub_name_formatter":0,
        "save_multi_sub":true,
        "custom_video_exts":[

        ],
        "fix_time_line":true,
        "topic":1,
        "suppliers_settings":{
            "xunlei":{
                "name":"xunlei",
                "root_url":"http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "search_url":"",
                "daily_download_limit":-1
            },
            "shooter":{
                "name":"shooter",
                "root_url":"https://www.shooter.cn/api/subapi.php",
                "search_url":"",
                "daily_download_limit":-1
            },
            "assrt":{
                "name":"assrt",
                "root_url":"https://api.assrt.net/v1",
                "search_url":"",
                "daily_download_limit":-1
            },
            "a4k":{
                "name":"a4k",
                "root_url":"https://www.a4k.net",
                "search_url":"/search?keyword=",
                "daily_download_limit":-1
            },
            "subhd":{
                "name":"subhd",
                "root_url":"https://subhd.tv",
                "search_url":"/search/%s",
                "daily_download_limit":20
            },
            "zimuku":{
                "name":"zimuku",
                "root_url":"https://zimuku.org",
                "search_url":"/search?q=%s",
                "daily_download_limit":20
            },
            "subtitle_best":{
                "name":"subtitle_best",
                "root_url":"https://api.subtitle.best/share-sub/v1",
                "search_url":"/search-movie",
                "daily_download_limit":-1
            }
        },
        "scan_logic":{
            "skip_chinese_movie":true,
            "skip_chinese_series":true
        },
        "task_queue":{
            "max_retry_times":3,
            "one_job_time_out":300,
            "interval":10,
            "expiration_time":90,
            "download_sub_during_x_days":7,
            "one_sub_download_interval":12,
            "check_pulic_ip_target_site":""
        },
        "download_file_cache":{
            "ttl":4320,
            "unit":"hour"
        }
    },
    "emby_settings":{
        "enable":true,
        "address_url":"http://192.168.1.*:8096",
        "api_key":"*",
        "max_request_video_number":3000,
        "skip_watched":true,
        "movie_paths_mapping":{
            "/media/movie":""
        },
        "series_paths_mapping":{
            "/media/Episodes":""
        },
        "auto_or_manual":true,
        "threads":3
    },
    "developer_settings":{
        "enable":false,
        "bark_server_address":""
    },
    "timeline_fixer_settings":{
        "max_offset_time":700,
        "min_offset":0.2
    },
    "experimental_function":{
        "auto_change_sub_encode":{
            "enable":false,
            "des_encode_type":0
        },
        "chs_cht_changer":{
            "enable":false,
            "des_chinese_language_type":0
        },
        "remote_chrome_settings":{
            "enable":false,
            "remote_docker_url":"",
            "remote_adblock_path":"",
            "remote_user_data_dir":""
        },
        "api_key_settings":{
            "enabled":false,
            "key":""
        },
        "local_chrome_settings":{
            "enabled":false,
            "local_chrome_exe_f_path":""
        },
        "share_sub_settings":{
            "share_sub_enabled":false
        },
        "extend_log":{
            "SysLog":{
                "enable":false,
                "network":"",
                "address":"",
                "priority":0,
                "tag":""
            }
        }
    }
}

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

[ERROR]: 2023-11-14 13:24:22 - MovieNeedDlSub /media/movie/东北警察故事2 (2023)/树上有个好地方2：美术老师的放羊班 (2023) - 1080p H.264 AAC.mp4 GetVideoInfoFromFileFullPath.IsFakeBDMVWorked == false
[WARNING]: 2023-11-14 13:24:22 - movie /media/movie/疾速营救 (2023)/疾速营救 (2023) - 2160p H.265 Atmos DDP5.1.mkv downloadQueue isExisted
[INFO]: 2023-11-14 13:24:23 - query queue, sleep 30s
[INFO]: 2023-11-14 13:24:31 - query queue, sleep 30s
[INFO]: 2023-11-14 13:24:54 - query queue, sleep 30s
[INFO]: 2023-11-14 13:25:02 - query queue, sleep 30s
[INFO]: 2023-11-14 13:25:25 - query queue, sleep 30s
[INFO]: 2023-11-14 13:25:33 - query queue, sleep 30s
[INFO]: 2023-11-14 13:25:56 - query queue, sleep 30s
[INFO]: 2023-11-14 13:26:04 - query queue, sleep 30s
[INFO]: 2023-11-14 13:26:28 - query queue, sleep 30s
[INFO]: 2023-11-14 13:26:35 - query queue, sleep 30s
[INFO]: 2023-11-14 13:27:00 - query queue, sleep 30s
[INFO]: 2023-11-14 13:27:06 - query queue, sleep 30s
[INFO]: 2023-11-14 13:27:31 - query queue, sleep 30s
[INFO]: 2023-11-14 13:27:37 - query queue, sleep 30s
[INFO]: 2023-11-14 13:28:02 - query queue, sleep 30s
[INFO]: 2023-11-14 13:28:09 - query queue, sleep 30s
[INFO]: 2023-11-14 13:28:33 - query queue, sleep 30s
[ERROR]: 2023-11-14 13:28:39 - Downloader.QueueDownloader() panic
[ERROR]: 2023-11-14 13:28:39 - goroutine 867 [running]:
github.com/ChineseSubFinder/ChineseSubFinder/pkg.PrintPanicStack(0xc000691c80?)
	/root/go/src/pkg/util.go:716 +0x3d
github.com/ChineseSubFinder/ChineseSubFinder/pkg/downloader.(*Downloader).queueDownloaderLocal.func1()
	/root/go/src/pkg/downloader/queue_local.go:25 +0x7a
panic({0x1141960, 0x26be9e0})
	/usr/lib/go/src/runtime/panic.go:844 +0x258
github.com/ChineseSubFinder/ChineseSubFinder/pkg/imdb_helper.IsChineseVideo(0xc00070c738, {{0xc0009cb4d0, 0xa}, {0xc0009cb4a0, 0x6}, {0xc0009cb4f8, 0x6}, 0xffffffffffffffff, 0xffffffffffffffff, {0xc0009cb340, ...}, ...})
	/root/go/src/pkg/imdb_helper/imdb.go:180 +0x1e9
github.com/ChineseSubFinder/ChineseSubFinder/pkg/logic/series_helper.SkipChineseSeries(0xc00070c738, {0xc00058cf60, 0x1d})
	/root/go/src/pkg/logic/series_helper/seriesHelper.go:167 +0x145
github.com/ChineseSubFinder/ChineseSubFinder/pkg/logic/sub_supplier.(*SubSupplierHub).SeriesNeedDlSub(0xc0004d0300, 0x0?, {0xc00058cf60, 0x1d}, 0x0, 0x0?)
	/root/go/src/pkg/logic/sub_supplier/subSupplierHub.go:101 +0x91
github.com/ChineseSubFinder/ChineseSubFinder/pkg/downloader.(*Downloader).queueDownloaderLocal(0xc00063c000)
	/root/go/src/pkg/downloader/queue_local.go:191 +0xcba
github.com/ChineseSubFinder/ChineseSubFinder/pkg/downloader.(*Downloader).QueueDownloader(0xc00063c000)
	/root/go/src/pkg/downloader/downloader.go:196 +0x1e
github.com/robfig/cron/v3.FuncJob.Run(0xc70de6e61d6?)
	/root/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1a
github.com/robfig/cron/v3.DelayIfStillRunning.func1.1()
	/root/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/chain.go:71 +0x1aa
github.com/robfig/cron/v3.FuncJob.Run(0xc000118290?)
	/root/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/root/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
	/root/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad

[INFO]: 2023-11-14 13:28:39 - Download.SupplierCheck() Start ...
[INFO]: 2023-11-14 13:28:39 - PreDownloadProcess.Init().Check().Wait()...
[INFO]: 2023-11-14 13:28:39 - PreDownloadProcess.Init() Start...
[INFO]: 2023-11-14 13:28:39 - ClearRodTmpRootFolder Done
[INFO]: 2023-11-14 13:28:39 - PreDownloadProcess.Init() End
[INFO]: 2023-11-14 13:28:39 - PreDownloadProcess.Check() Start...
[INFO]: 2023-11-14 13:28:39 - UseHttpProxy = false
[INFO]: 2023-11-14 13:28:39 - UrlConnectednessTest Target Site https://baidu.com Speed: 199 ms, Status: true
[INFO]: 2023-11-14 13:28:39 - Check Sub Supplier Start...
[INFO]: 2023-11-14 13:28:39 - xunlei Check Alive = true, Speed = 203 ms
[ERROR]: 2023-11-14 13:28:39 - a4k CheckAlive.Get Get "https://www.a4k.net": dial tcp: lookup www.a4k.net on 192.168.1.251:53: no such host
[WARNING]: 2023-11-14 13:28:39 - a4k Check Alive = false
[INFO]: 2023-11-14 13:28:39 - assrt CheckAlive UserInfo.Status: 0 UserInfo.Quota: 5
[INFO]: 2023-11-14 13:28:39 - assrt Check Alive = true, Speed = 342 ms
[INFO]: 2023-11-14 13:28:40 - subtitle_best Check Alive = true, Speed = 1224 ms
[INFO]: 2023-11-14 13:28:42 - shooter Check Alive = true, Speed = 2443 ms
[INFO]: 2023-11-14 13:28:42 - Alive Supplier: xunlei
[INFO]: 2023-11-14 13:28:42 - Alive Supplier: shooter
[INFO]: 2023-11-14 13:28:42 - Alive Supplier: assrt
[INFO]: 2023-11-14 13:28:42 - Alive Supplier: subtitle_best
[INFO]: 2023-11-14 13:28:42 - Check Sub Supplier End
[INFO]: 2023-11-14 13:28:42 - MovieFolder Index 0 -- /media/movie
[INFO]: 2023-11-14 13:28:42 - SeriesPaths Index 0 -- /media/Episodes
[INFO]: 2023-11-14 13:28:42 - PreDownloadProcess.Check() End
[INFO]: 2023-11-14 13:28:42 - PreDownloadProcess.Wait() Done.
[INFO]: 2023-11-14 13:28:42 - Download.SupplierCheck() End
[INFO]: 2023-11-14 13:28:43 - query queue, sleep 30s
[INFO]: 2023-11-14 13:29:04 - query queue, sleep 30s
[INFO]: 2023-11-14 13:29:14 - query queue, sleep 30s
[INFO]: 2023-11-14 13:29:34 - VideoScanAndRefreshHelper finished, cost: 6.091931396366666 min
[INFO]: 2023-11-14 13:29:34 - Video Scan End
[INFO]: 2023-11-14 13:29:34 - ------------------------------------

**Comment by kpnew9** [comment]
没有人可以解答一下吗？
