### ISSUE TITLE
无法正常运行，看终端机显示是无法读取配置文件。

### ISSUE THREAD

**Issue by Fishes2021** [ChineseSubFinder/ChineseSubFinder#91]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

chinesesubfinder 版本: v0.18.1

环境: docker

## 你遇到什么问题了？

安装完成并配置完成电影和剧集的目录后，配置文件编码就变成了GBK，然后运行时在终端机中不停的显示如下内容：
[INFO]: 2021-10-23 23:21:56 - ChineseSubFinder Version:                         
panic: GetConfig - initConfigure error reading config:While parsing config: yaml
: invalid leading UTF-8 octet                                                   
                                                                                
goroutine 1 [running]:                                                          
github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig.func1()           
        /homelab/buildspace/internal/pkg/config.go:16 +0x274                    
sync.(*Once).doSlow(0x64, 0xc00047e770)                                         
        /usr/local/go/src/sync/once.go:68 +0xd2                                 
sync.(*Once).Do(...)                                                            
        /usr/local/go/src/sync/once.go:59                                       
github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig()                 
        /homelab/buildspace/internal/pkg/config.go:13 +0x31                     
main.init.0()                                                                   
        /homelab/buildspace/cmd/chinesesubfinder/main.go:32 +0xb3               
^C[cont-finish.d] executing container finish scripts...                         
[cont-finish.d] done.                                                           
[s6-finish] waiting for services.                                               
[s6-finish] sending all processes the TERM signal.                              
^C[s6-finish] sending all processes the KILL signal and exiting.                

## 你的问题弄重现嘛？

能够重新

## 你期望的结果

正常运行即可

## 出错的日志信息可以复制一些出来吗？

<html>
<body>
<h2 style="text-align: center; color: rgb(0, 0, 0); font-family: &quot;Lucida Console&quot;, Consola, Monaco, monospace, &quot;Courier New&quot;, Courier, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">allanpk716-chinesesubfinder1</h2>

date | stream | content
-- | -- | --
2021-10-23 15:27:13 | stdout | /homelab/buildspace/cmd/chinesesubfinder/main.go:32 +0xb3
2021-10-23 15:27:13 | stdout | main.init.0()
2021-10-23 15:27:13 | stdout | /homelab/buildspace/internal/pkg/config.go:13 +0x31
2021-10-23 15:27:13 | stdout | github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig()
2021-10-23 15:27:13 | stdout | /usr/local/go/src/sync/once.go:59
2021-10-23 15:27:13 | stdout | sync.(*Once).Do(...)
2021-10-23 15:27:13 | stdout | /usr/local/go/src/sync/once.go:68 +0xd2
2021-10-23 15:27:13 | stdout | sync.(*Once).doSlow(0x64, 0xc00047c930)
2021-10-23 15:27:13 | stdout | /homelab/buildspace/internal/pkg/config.go:16 +0x274
2021-10-23 15:27:13 | stdout | github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig.func1()
2021-10-23 15:27:13 | stdout | goroutine 1 [running]:
2021-10-23 15:27:13 | stdout |  
2021-10-23 15:27:13 | stdout | panic: GetConfig - initConfigure error reading config:While parsing config: yaml: invalid leading UTF-8 octet
2021-10-23 15:27:13 | stdout | [INFO]: 2021-10-23 23:27:13 - ChineseSubFinder Version:
2021-10-23 15:27:13 | stdout | (EE)
2021-10-23 15:27:13 | stdout | and start again.
2021-10-23 15:27:13 | stdout | If this server is no longer running, remove /tmp/.X99-lock
2021-10-23 15:27:13 | stdout | (EE) Server is already active for display 99
2021-10-23 15:27:13 | stdout | Fatal server error:
2021-10-23 15:27:13 | stdout | (EE)
2021-10-23 15:27:12 | stdout | /homelab/buildspace/cmd/chinesesubfinder/main.go:32 +0xb3
2021-10-23 15:27:12 | stdout | main.init.0()
2021-10-23 15:27:12 | stdout | /homelab/buildspace/internal/pkg/config.go:13 +0x31
2021-10-23 15:27:12 | stdout | github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig()
2021-10-23 15:27:12 | stdout | /usr/local/go/src/sync/once.go:59
2021-10-23 15:27:12 | stdout | sync.(*Once).Do(...)
2021-10-23 15:27:12 | stdout | /usr/local/go/src/sync/once.go:68 +0xd2
2021-10-23 15:27:12 | stdout | sync.(*Once).doSlow(0x64, 0xc000138700)
2021-10-23 15:27:12 | stdout | /homelab/buildspace/internal/pkg/config.go:16 +0x274
2021-10-23 15:27:12 | stdout | github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig.func1()
2021-10-23 15:27:12 | stdout | goroutine 1 [running]:
2021-10-23 15:27:12 | stdout |  
2021-10-23 15:27:12 | stdout | panic: GetConfig - initConfigure error reading config:While parsing config: yaml: invalid leading UTF-8 octet
2021-10-23 15:27:12 | stdout | [INFO]: 2021-10-23 23:27:12 - ChineseSubFinder Version:
2021-10-23 15:27:12 | stdout | (EE)
2021-10-23 15:27:12 | stdout | and start again.
2021-10-23 15:27:12 | stdout | If this server is no longer running, remove /tmp/.X99-lock
2021-10-23 15:27:12 | stdout | (EE) Server is already active for display 99
2021-10-23 15:27:12 | stdout | Fatal server error:
2021-10-23 15:27:12 | stdout | (EE)
2021-10-23 15:27:11 | stdout | /homelab/buildspace/cmd/chinesesubfinder/main.go:32 +0xb3
2021-10-23 15:27:11 | stdout | main.init.0()
2021-10-23 15:27:11 | stdout | /homelab/buildspace/internal/pkg/config.go:13 +0x31
2021-10-23 15:27:11 | stdout | github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig()
2021-10-23 15:27:11 | stdout | /usr/local/go/src/sync/once.go:59
2021-10-23 15:27:11 | stdout | sync.(*Once).Do(...)
2021-10-23 15:27:11 | stdout | /usr/local/go/src/sync/once.go:68 +0xd2
2021-10-23 15:27:11 | stdout | sync.(*Once).doSlow(0x64, 0xc000478af0)
2021-10-23 15:27:11 | stdout | /homelab/buildspace/internal/pkg/config.go:16 +0x274
2021-10-23 15:27:11 | stdout | github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig.func1()
2021-10-23 15:27:11 | stdout | goroutine 1 [running]:
2021-10-23 15:27:11 | stdout |  
2021-10-23 15:27:11 | stdout | panic: GetConfig - initConfigure error reading config:While parsing config: yaml: invalid leading UTF-8 octet
2021-10-23 15:27:11 | stdout | [INFO]: 2021-10-23 23:27:11 - ChineseSubFinder Version:
2021-10-23 15:27:11 | stdout | (EE)
2021-10-23 15:27:11 | stdout | and start again.
2021-10-23 15:27:11 | stdout | If this server is no longer running, remove /tmp/.X99-lock
2021-10-23 15:27:11 | stdout | (EE) Server is already active for display 99
2021-10-23 15:27:11 | stdout | Fatal server error:
2021-10-23 15:27:11 | stdout | (EE)
2021-10-23 15:27:10 | stdout | /homelab/buildspace/cmd/chinesesubfinder/main.go:32 +0xb3
2021-10-23 15:27:10 | stdout | main.init.0()
2021-10-23 15:27:10 | stdout | /homelab/buildspace/internal/pkg/config.go:13 +0x31
2021-10-23 15:27:10 | stdout | github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig()
2021-10-23 15:27:10 | stdout | /usr/local/go/src/sync/once.go:59
2021-10-23 15:27:10 | stdout | sync.(*Once).Do(...)
2021-10-23 15:27:10 | stdout | /usr/local/go/src/sync/once.go:68 +0xd2
2021-10-23 15:27:10 | stdout | sync.(*Once).doSlow(0x64, 0xc000136a10)
2021-10-23 15:27:10 | stdout | /homelab/buildspace/internal/pkg/config.go:16 +0x274
2021-10-23 15:27:10 | stdout | github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig.func1()
2021-10-23 15:27:10 | stdout | goroutine 1 [running]:
2021-10-23 15:27:10 | stdout |  
2021-10-23 15:27:10 | stdout | panic: GetConfig - initConfigure error reading config:While parsing config: yaml: invalid leading UTF-8 octet
2021-10-23 15:27:10 | stdout | [INFO]: 2021-10-23 23:27:10 - ChineseSubFinder Version:
2021-10-23 15:27:10 | stdout | (EE)
2021-10-23 15:27:10 | stdout | and start again.
2021-10-23 15:27:10 | stdout | If this server is no longer running, remove /tmp/.X99-lock
2021-10-23 15:27:10 | stdout | (EE) Server is already active for display 99
2021-10-23 15:27:10 | stdout | Fatal server error:
2021-10-23 15:27:10 | stdout | (EE)
2021-10-23 15:27:09 | stdout | /homelab/buildspace/cmd/chinesesubfinder/main.go:32 +0xb3
2021-10-23 15:27:09 | stdout | main.init.0()
2021-10-23 15:27:09 | stdout | /homelab/buildspace/internal/pkg/config.go:13 +0x31
2021-10-23 15:27:09 | stdout | github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig()
2021-10-23 15:27:09 | stdout | /usr/local/go/src/sync/once.go:59
2021-10-23 15:27:09 | stdout | sync.(*Once).Do(...)
2021-10-23 15:27:09 | stdout | /usr/local/go/src/sync/once.go:68 +0xd2
2021-10-23 15:27:09 | stdout | sync.(*Once).doSlow(0x64, 0xc0004768c0)
2021-10-23 15:27:09 | stdout | /homelab/buildspace/internal/pkg/config.go:16 +0x274
2021-10-23 15:27:09 | stdout | github.com/allanpk716/ChineseSubFinder/internal/pkg.GetConfig.func1()
2021-10-23 15:27:09 | stdout | goroutine 1 [running]:
2021-10-23 15:27:09 | stdout |  
2021-10-23 15:27:09 | stdout | panic: GetConfig - initConfigure error reading config:While parsing config: yaml: invalid leading UTF-8 octet
2021-10-23 15:27:09 | stdout | [INFO]: 2021-10-23 23:27:09 - ChineseSubFinder Version:
2021-10-23 15:27:09 | stdout | (EE)

</body>
</html>

**Comment by allanpk716** [comment]
提示编码问题，就换编辑器，sublime text 、notepad++

**Comment by Fishes2021** [comment]
编码问题解决了，已成功运行。谢谢

**Comment by allanpk716** [comment]
> 编码问题解决了，已成功运行。谢谢

客气
